export const copy = {
  es: {
    nav: ['Proyectos', 'Stack', 'Sobre mí'],
    available: 'Disponible para proyectos y empleo',
    intro: 'De la interfaz a la lógica del negocio.',
    intro2: 'Conecto las piezas que hacen funcionar tu producto.',
    view: 'Ver proyectos',
    talk: 'Hablemos',
    explore: 'Explora mi trabajo',
    signature: 'DESARROLLO · CALIDAD · ENTREGA',
    layers: 'Explorar capas',
    closeLayers: 'Unir capas',
    layerHint: 'Una visión completa. Cada pieza conectada.',
    workLabel: '01 / TRABAJO SELECCIONADO',
    workTitle: 'Ideas que ya',
    workTitle2: 'están funcionando.',
    workIntro:
      'Desarrollo de productos, presencia digital y mejora de plataformas existentes. Tres contextos, una misma atención al detalle.',
    details: 'Mi contribución',
    hide: 'Cerrar detalles',
    visit: 'Visitar sitio',
    challenge: 'La necesidad',
    contribution: 'Mi aporte',
    stackLabel: '02 / DEL CONCEPTO AL SISTEMA',
    stackTitle: 'Todo conectado.',
    stackTitle2: 'De principio a fin.',
    stackIntro:
      'Explora las tecnologías con las que trabajo y cómo se conectan para convertir una acción en un resultado.',
    front: 'Interfaz',
    back: 'Lógica de negocio',
    data: 'Datos',
    simulate: 'Ejecutar recorrido',
    replay: 'Repetir recorrido',
    running: 'Recorriendo el sistema',
    simulation: 'Demostración conceptual',
    stages: [
      'Listo para comenzar',
      'La interfaz recibe tu solicitud',
      'El backend procesa la lógica',
      'La base de datos responde',
      'El resultado vuelve a la interfaz',
    ],
    systemText: 'Una solicitud. Tres capas. Una experiencia.',
    backendText:
      'Servicios y APIs que conectan las necesidades del negocio con el producto.',
    dataText:
      'Datos relacionales y documentos, según lo que necesita cada solución.',
    frontendText:
      'Interfaces que hacen sencillo interactuar con sistemas complejos.',
    enterprise: 'SOLUCIONES EMPRESARIALES',
    enterpriseText:
      'Experiencia con Microsoft Dynamics 365 y procesos de negocio.',
    delivery: 'CALIDAD Y ENTREGA',
    deliveryText:
      'Automatización de pruebas, integración continua y despliegue.',
    aboutLabel: '03 / DETRÁS DEL CÓDIGO',
    aboutTitle: 'Pienso en el producto.',
    aboutTitle2: 'Cuido cada pieza.',
    bio: 'Soy Wilder Mancera, desarrollador full stack. Me interesa conectar todas las partes de un producto: cómo se ve, cómo se utiliza y cómo funciona por dentro.',
    bio2: 'Trabajo con frontend, backend y datos, y acompaño el desarrollo con automatización de pruebas y procesos de entrega. Busco soluciones claras para sus usuarios y bien estructuradas para quienes las mantienen.',
    principles: [
      [
        'Visión integral',
        'De la experiencia de usuario a los servicios y datos.',
      ],
      [
        'Calidad desde el inicio',
        'Pruebas y atención al detalle durante el desarrollo.',
      ],
      [
        'Evolución continua',
        'Mejorar lo existente y construir pensando en el siguiente paso.',
      ],
    ],
    contactLabel: '04 / CONSTRUYAMOS LO SIGUIENTE',
    contactTitle: 'Las buenas ideas',
    contactTitle2: 'empiezan hablando.',
    contactIntro:
      '¿Un producto por construir o un equipo al que sumarme? Me gustaría conocerlo.',
    projectIntent: 'Tengo un proyecto',
    jobIntent: 'Hablemos de una oportunidad',
    email: 'Escríbeme',
    copy: 'Copiar correo',
    copied: 'Correo copiado',
    copyError: 'No se pudo copiar. Puedes seleccionar el correo.',
    footer: 'Desarrollo con intención.',
    skip: 'Saltar al contenido',
    selectTech: 'Seleccionar tecnología',
  },
  en: {
    nav: ['Projects', 'Stack', 'About'],
    available: 'Open to projects and opportunities',
    intro: 'From interface to business logic.',
    intro2: 'I connect the pieces that make your product work.',
    view: 'View projects',
    talk: 'Let’s talk',
    explore: 'Explore my work',
    signature: 'DEVELOPMENT · QUALITY · DELIVERY',
    layers: 'Explore layers',
    closeLayers: 'Bring layers together',
    layerHint: 'A complete perspective. Every piece connected.',
    workLabel: '01 / SELECTED WORK',
    workTitle: 'Ideas already',
    workTitle2: 'out in the world.',
    workIntro:
      'Product development, digital presence, and improvements to existing platforms. Three contexts, the same attention to detail.',
    details: 'My contribution',
    hide: 'Close details',
    visit: 'Visit website',
    challenge: 'The need',
    contribution: 'My contribution',
    stackLabel: '02 / FROM CONCEPT TO SYSTEM',
    stackTitle: 'All connected.',
    stackTitle2: 'From end to end.',
    stackIntro:
      'Explore the technologies I work with and how they connect to turn an action into a result.',
    front: 'Interface',
    back: 'Business logic',
    data: 'Data',
    simulate: 'Run the flow',
    replay: 'Replay the flow',
    running: 'Following the request',
    simulation: 'Conceptual demonstration',
    stages: [
      'Ready to begin',
      'The interface receives your request',
      'The backend processes the logic',
      'The database responds',
      'The result returns to the interface',
    ],
    systemText: 'One request. Three layers. One experience.',
    backendText:
      'Services and APIs that connect business needs to the product.',
    dataText:
      'Relational data and documents, chosen around each solution’s needs.',
    frontendText:
      'Interfaces that make complex systems simple to interact with.',
    enterprise: 'BUSINESS SOLUTIONS',
    enterpriseText:
      'Experience with Microsoft Dynamics 365 and business processes.',
    delivery: 'QUALITY & DELIVERY',
    deliveryText: 'Test automation, continuous integration, and deployment.',
    aboutLabel: '03 / BEHIND THE CODE',
    aboutTitle: 'I think in products.',
    aboutTitle2: 'I care for every piece.',
    bio: 'I’m Wilder Mancera, a full stack developer. I enjoy connecting every part of a product: how it looks, how people use it, and how it works underneath.',
    bio2: 'I work across frontend, backend, and data, supporting development with test automation and delivery processes. I aim for solutions that are clear to their users and well structured for the teams maintaining them.',
    principles: [
      ['End-to-end perspective', 'From user experience to services and data.'],
      [
        'Quality from the start',
        'Testing and attention to detail throughout development.',
      ],
      [
        'Continuous evolution',
        'Improving existing products and building for the next step.',
      ],
    ],
    contactLabel: '04 / LET’S BUILD WHAT’S NEXT',
    contactTitle: 'Good ideas start',
    contactTitle2: 'with a conversation.',
    contactIntro:
      'A product to build or a team to join? I’d love to hear about it.',
    projectIntent: 'I have a project',
    jobIntent: 'Let’s discuss an opportunity',
    email: 'Email me',
    copy: 'Copy email',
    copied: 'Email copied',
    copyError: 'Could not copy. You can select the email address.',
    footer: 'Development with intention.',
    skip: 'Skip to content',
    selectTech: 'Select technology',
  },
};
export const projects = [
  {
    id: 'delta',
    name: 'DeltaForex',
    type: {
      es: 'PLATAFORMA / COMUNIDAD DE TRADING',
      en: 'PLATFORM / TRADING COMMUNITY',
    },
    url: 'https://deltaforex.org/',
    tech: ['React', 'Node.js', 'PostgreSQL'],
    practices: ['QA Automation', 'CI/CD', 'DevOps'],
    summary: {
      es: 'Una comunidad. Toda la información conectada.',
      en: 'One community. All the information connected.',
    },
    need: {
      es: 'Organizar el seguimiento de cuentas, resultados e historial para una comunidad de trading.',
      en: 'Organize account, performance, and history tracking for a trading community.',
    },
    contribution: {
      es: 'Desarrollo de funcionalidades de seguimiento e interfaces para consultar información de cuentas, junto con automatización de pruebas, CI/CD y trabajo de DevOps.',
      en: 'Development of tracking features and interfaces for account information, alongside test automation, CI/CD, and DevOps work.',
    },
  },
  {
    id: 'techbrains',
    name: 'TechBrains',
    type: {
      es: 'SITIO CORPORATIVO / SOFTWARE',
      en: 'CORPORATE WEBSITE / SOFTWARE',
    },
    url: 'https://www.techbrains.com.do/',
    tech: ['React', '.NET', 'SQL Server'],
    practices: ['QA Automation', 'CI/CD'],
    summary: {
      es: 'Una presencia digital para construir nuevas oportunidades.',
      en: 'A digital presence to create new opportunities.',
    },
    need: {
      es: 'Dar a conocer una startup de desarrollo y presentar sus servicios a potenciales clientes.',
      en: 'Introduce a development startup and present its services to prospective clients.',
    },
    contribution: {
      es: 'Desarrollo de la plataforma corporativa, conectando la presentación de servicios con la implementación técnica, automatización de pruebas y procesos de CI/CD.',
      en: 'Development of the corporate platform, connecting the service presentation with technical implementation, test automation, and CI/CD processes.',
    },
  },
  {
    id: 'cargo',
    name: 'Torneo BM Cargo',
    type: { es: 'PLATAFORMA / INSCRIPCIONES', en: 'PLATFORM / REGISTRATION' },
    url: 'https://inscripciontorneo.bmcargo.com/',
    tech: ['React', 'Node.js', 'MongoDB'],
    practices: ['QA Automation', 'CI/CD'],
    summary: {
      es: 'Evolucionar una plataforma. Cuidar la experiencia.',
      en: 'Evolving a platform. Caring for the experience.',
    },
    need: {
      es: 'Actualizar y corregir una plataforma existente de inscripción de jugadores y patrocinadores a un torneo.',
      en: 'Update and fix an existing platform for tournament player and sponsor registrations.',
    },
    contribution: {
      es: 'Modificaciones y correcciones en distintas partes del proyecto existente, acompañadas de automatización de pruebas y procesos de CI/CD.',
      en: 'Changes and fixes across different parts of the existing project, supported by test automation and CI/CD processes.',
    },
  },
];
